server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geek
    username: geek
    password: geek
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        temp:
#          use_jdbc_metadata_defaults: false