server:
  port: 8080
  servlet:
    context-path: /interview
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/geek
    username: geek
    password: geek
  thymeleaf:
    check-template: true
    check-template-location: true